services:
  mysql:
    image: mysql:8.0
    container_name: mysql_smartnotify
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartnotify

    ports:
      - "3304:3306"

    volumes:
      - mysql_smartnotify_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_smartnotify
    restart: always

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "8085:80"

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_smartnotify_data: